-- =============================================================================
-- 02_warehouses.sql - Warehouse Configuration
-- =============================================================================
-- Run as: SYSADMIN
-- =============================================================================

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST WAREHOUSE_SIZE='X-SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='Data ingestion via Snowpipe';
CREATE WAREHOUSE IF NOT EXISTS WH_DBT_DEV WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='dbt Cloud DEV';
CREATE WAREHOUSE IF NOT EXISTS WH_DBT_TEST WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='dbt Cloud TEST';
CREATE WAREHOUSE IF NOT EXISTS WH_DBT_PROD WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='dbt Cloud PROD - hourly';
CREATE WAREHOUSE IF NOT EXISTS WH_BI WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='Snowsight dashboards';
CREATE WAREHOUSE IF NOT EXISTS WH_ADHOC WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE STATEMENT_TIMEOUT_IN_SECONDS=900 COMMENT='Ad-hoc analyst queries - 15 min timeout';
