-- =============================================================================
-- 03_databases.sql - Multi-Environment Databases
-- =============================================================================
USE ROLE SYSADMIN;

-- DEV
CREATE DATABASE IF NOT EXISTS RAW_DB_DEV DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Raw - DEV';
CREATE DATABASE IF NOT EXISTS STAGING_DB_DEV DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Staging - DEV';
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB_DEV DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Analytics - DEV';
CREATE DATABASE IF NOT EXISTS GOVERNANCE_DB_DEV DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Governance - DEV';

-- TEST
CREATE DATABASE IF NOT EXISTS RAW_DB_TEST DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Raw - TEST';
CREATE DATABASE IF NOT EXISTS STAGING_DB_TEST DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Staging - TEST';
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB_TEST DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Analytics - TEST';
CREATE DATABASE IF NOT EXISTS GOVERNANCE_DB_TEST DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Governance - TEST';

-- PROD
CREATE DATABASE IF NOT EXISTS RAW_DB_PROD DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Raw - PROD';
CREATE DATABASE IF NOT EXISTS STAGING_DB_PROD DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Staging - PROD';
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB_PROD DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Analytics - PROD';
CREATE DATABASE IF NOT EXISTS GOVERNANCE_DB_PROD DATA_RETENTION_TIME_IN_DAYS=1 COMMENT='Governance - PROD';
