-- See full file in local repo: snowflake/04_schemas.sql
-- Creates all schemas across DEV/TEST/PROD for RAW_DB, STAGING_DB, ANALYTICS_DB, GOVERNANCE_DB
-- Schemas: FLUIDRAPRO_RAW, SALESFORCE_RAW, ORACLE_RAW, REVENUE_RAW, STAGING, INTERMEDIATE, DIMENSIONS, FACTS, MARTS, REPORTING, AUDIT, MONITORING, DATA_QUALITY

USE ROLE SYSADMIN;

-- PROD schemas
CREATE SCHEMA IF NOT EXISTS RAW_DB_PROD.FLUIDRAPRO_RAW;
CREATE SCHEMA IF NOT EXISTS RAW_DB_PROD.SALESFORCE_RAW;
CREATE SCHEMA IF NOT EXISTS RAW_DB_PROD.ORACLE_RAW;
CREATE SCHEMA IF NOT EXISTS RAW_DB_PROD.REVENUE_RAW;
CREATE SCHEMA IF NOT EXISTS STAGING_DB_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB_PROD.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB_PROD.DIMENSIONS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB_PROD.FACTS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB_PROD.MARTS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB_PROD.REPORTING;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB_PROD.AUDIT;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB_PROD.MONITORING;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB_PROD.DATA_QUALITY;
