-- See full file in local repo: snowflake/05_grants.sql
-- Full RBAC grant matrix for all roles across DEV/TEST/PROD
USE ROLE SECURITYADMIN;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE WH_INGEST TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE WH_DBT_DEV TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON WAREHOUSE WH_DBT_TEST TO ROLE DBT_TEST_ROLE;
GRANT USAGE ON WAREHOUSE WH_DBT_PROD TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON WAREHOUSE WH_BI TO ROLE BI_ROLE;
GRANT USAGE ON WAREHOUSE WH_ADHOC TO ROLE ANALYST_ROLE;

-- PROD: DBT_PROD_ROLE
GRANT USAGE ON DATABASE RAW_DB_PROD TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DB_PROD TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_DB_PROD TO ROLE DBT_PROD_ROLE;
GRANT ALL ON DATABASE STAGING_DB_PROD TO ROLE DBT_PROD_ROLE;
GRANT ALL ON DATABASE ANALYTICS_DB_PROD TO ROLE DBT_PROD_ROLE;

-- PROD: BI_ROLE (read marts + reporting only)
GRANT USAGE ON DATABASE ANALYTICS_DB_PROD TO ROLE BI_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS_DB_PROD.MARTS TO ROLE BI_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS_DB_PROD.REPORTING TO ROLE BI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_DB_PROD.MARTS TO ROLE BI_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS_DB_PROD.REPORTING TO ROLE BI_ROLE;

-- PROD: ANALYST_ROLE
GRANT USAGE ON DATABASE ANALYTICS_DB_PROD TO ROLE ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_DB_PROD TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DB_PROD TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE ANALYTICS_DB_PROD TO ROLE ANALYST_ROLE;
