-- 06_future_grants.sql - Auto-permissions for new dbt objects
USE ROLE SECURITYADMIN;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DB_PROD.FLUIDRAPRO_RAW TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB_PROD.MARTS TO ROLE BI_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB_PROD.REPORTING TO ROLE BI_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB_PROD.DIMENSIONS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB_PROD.FACTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB_PROD.MARTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB_PROD.REPORTING TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING_DB_PROD.STAGING TO ROLE ANALYST_ROLE;
