-- 07_storage_integration.sql - S3 Integration
USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS S3_FLUIDRA_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::REPLACE_WITH_AWS_ACCOUNT_ID:role/snowflake-fluidra-access'
  STORAGE_ALLOWED_LOCATIONS = ('s3://fluidra-data-lake/raw/');

GRANT USAGE ON INTEGRATION S3_FLUIDRA_INTEGRATION TO ROLE DATA_ENGINEER_ROLE;
