-- 08_resource_monitors.sql - Cost Controls
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_ACCOUNT WITH CREDIT_QUOTA=100 FREQUENCY=MONTHLY START_TIMESTAMP=IMMEDIATELY TRIGGERS ON 75 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
CREATE RESOURCE MONITOR IF NOT EXISTS RM_DBT_PROD WITH CREDIT_QUOTA=50 FREQUENCY=MONTHLY START_TIMESTAMP=IMMEDIATELY TRIGGERS ON 50 PERCENT DO NOTIFY ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO SUSPEND;
CREATE RESOURCE MONITOR IF NOT EXISTS RM_BI WITH CREDIT_QUOTA=30 FREQUENCY=MONTHLY START_TIMESTAMP=IMMEDIATELY TRIGGERS ON 50 PERCENT DO NOTIFY ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO SUSPEND;

ALTER WAREHOUSE WH_DBT_PROD SET RESOURCE_MONITOR = RM_DBT_PROD;
ALTER WAREHOUSE WH_BI SET RESOURCE_MONITOR = RM_BI;
