-- 09_users.sql - Service Accounts
USE ROLE SECURITYADMIN;

CREATE USER IF NOT EXISTS SVC_DBT_DEV DEFAULT_ROLE=DBT_DEV_ROLE DEFAULT_WAREHOUSE=WH_DBT_DEV MUST_CHANGE_PASSWORD=FALSE COMMENT='dbt Cloud - DEV';
CREATE USER IF NOT EXISTS SVC_DBT_TEST DEFAULT_ROLE=DBT_TEST_ROLE DEFAULT_WAREHOUSE=WH_DBT_TEST MUST_CHANGE_PASSWORD=FALSE COMMENT='dbt Cloud - TEST';
CREATE USER IF NOT EXISTS SVC_DBT_PROD DEFAULT_ROLE=DBT_PROD_ROLE DEFAULT_WAREHOUSE=WH_DBT_PROD MUST_CHANGE_PASSWORD=FALSE COMMENT='dbt Cloud - PROD';
CREATE USER IF NOT EXISTS SVC_INGEST DEFAULT_ROLE=DATA_ENGINEER_ROLE DEFAULT_WAREHOUSE=WH_INGEST MUST_CHANGE_PASSWORD=FALSE COMMENT='Ingestion service';

GRANT ROLE DBT_DEV_ROLE TO USER SVC_DBT_DEV;
GRANT ROLE DBT_TEST_ROLE TO USER SVC_DBT_TEST;
GRANT ROLE DBT_PROD_ROLE TO USER SVC_DBT_PROD;
GRANT ROLE DATA_ENGINEER_ROLE TO USER SVC_INGEST;
