-- 10_file_formats.sql
USE ROLE DATA_ENGINEER_ROLE;
USE WAREHOUSE WH_INGEST;

CREATE FILE FORMAT IF NOT EXISTS RAW_DB_PROD.FLUIDRAPRO_RAW.FF_JSON TYPE='JSON' STRIP_OUTER_ARRAY=FALSE DATE_FORMAT='AUTO' TIMESTAMP_FORMAT='AUTO';
CREATE FILE FORMAT IF NOT EXISTS RAW_DB_PROD.SALESFORCE_RAW.FF_CSV TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null');
CREATE FILE FORMAT IF NOT EXISTS RAW_DB_PROD.FLUIDRAPRO_RAW.FF_PARQUET TYPE='PARQUET' SNAPPY_COMPRESSION=TRUE;
