-- 11_external_stages.sql
USE ROLE DATA_ENGINEER_ROLE;
USE WAREHOUSE WH_INGEST;

CREATE STAGE IF NOT EXISTS RAW_DB_PROD.FLUIDRAPRO_RAW.STG_FLUIDRAPRO_S3
  STORAGE_INTEGRATION=S3_FLUIDRA_INTEGRATION URL='s3://fluidra-data-lake/raw/fluidrapro/' FILE_FORMAT=RAW_DB_PROD.FLUIDRAPRO_RAW.FF_JSON;

CREATE STAGE IF NOT EXISTS RAW_DB_PROD.SALESFORCE_RAW.STG_SALESFORCE_S3
  STORAGE_INTEGRATION=S3_FLUIDRA_INTEGRATION URL='s3://fluidra-data-lake/raw/salesforce/' FILE_FORMAT=RAW_DB_PROD.SALESFORCE_RAW.FF_CSV;

CREATE STAGE IF NOT EXISTS RAW_DB_PROD.ORACLE_RAW.STG_ORACLE_S3
  STORAGE_INTEGRATION=S3_FLUIDRA_INTEGRATION URL='s3://fluidra-data-lake/raw/oracle/' FILE_FORMAT=RAW_DB_PROD.SALESFORCE_RAW.FF_CSV;

CREATE STAGE IF NOT EXISTS RAW_DB_PROD.REVENUE_RAW.STG_REVENUE_S3
  STORAGE_INTEGRATION=S3_FLUIDRA_INTEGRATION URL='s3://fluidra-data-lake/raw/revenue/' FILE_FORMAT=RAW_DB_PROD.SALESFORCE_RAW.FF_CSV;
