-- 12_raw_tables.sql
USE ROLE DATA_ENGINEER_ROLE;
USE WAREHOUSE WH_INGEST;

CREATE TABLE IF NOT EXISTS RAW_DB_PROD.FLUIDRAPRO_RAW.RAW_DEALERS_DATA (
  RECORD_METADATA VARCHAR(16777216),
  RECORD_CONTENT VARCHAR(16777216),
  EVENT_TIME TIMESTAMP_NTZ,
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  _FILE_NAME VARCHAR(512)
) COMMENT='Raw CDC events from Fluidra Pro Platform via Kafka';

CREATE TABLE IF NOT EXISTS RAW_DB_PROD.SALESFORCE_RAW.RAW_LEADS (RAW_DATA VARIANT) COMMENT='Salesforce Leads - awaiting integration';
CREATE TABLE IF NOT EXISTS RAW_DB_PROD.SALESFORCE_RAW.RAW_ACCOUNTS (RAW_DATA VARIANT) COMMENT='Salesforce Accounts - awaiting integration';
CREATE TABLE IF NOT EXISTS RAW_DB_PROD.ORACLE_RAW.RAW_DEALER_MASTER (RAW_DATA VARIANT) COMMENT='Oracle dealer master - awaiting integration';
CREATE TABLE IF NOT EXISTS RAW_DB_PROD.REVENUE_RAW.RAW_REVENUE_TRANSACTIONS (RAW_DATA VARIANT) COMMENT='PSOT revenue - awaiting integration';
