-- 13_snowpipe_and_streams.sql
USE ROLE DATA_ENGINEER_ROLE;
USE WAREHOUSE WH_INGEST;

CREATE PIPE IF NOT EXISTS RAW_DB_PROD.FLUIDRAPRO_RAW.PIPE_FLUIDRAPRO_CDC
  AUTO_INGEST=TRUE
  COMMENT='Auto-ingest Fluidra Pro CDC from S3'
AS COPY INTO RAW_DB_PROD.FLUIDRAPRO_RAW.RAW_DEALERS_DATA (RECORD_METADATA, RECORD_CONTENT, EVENT_TIME)
FROM (SELECT $1:metadata::VARCHAR, $1:content::VARCHAR, TRY_TO_TIMESTAMP_NTZ($1:event_time::STRING)
      FROM @RAW_DB_PROD.FLUIDRAPRO_RAW.STG_FLUIDRAPRO_S3)
ON_ERROR=CONTINUE;

CREATE STREAM IF NOT EXISTS RAW_DB_PROD.FLUIDRAPRO_RAW.STRM_RAW_DEALERS_DATA
  ON TABLE RAW_DB_PROD.FLUIDRAPRO_RAW.RAW_DEALERS_DATA APPEND_ONLY=TRUE;
